spring:
  datasource:
    url: jdbc:mysql://localhost:3306/udemy?useSSL=false
    username: root
    password: password
    driver:
      class: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
